version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: electroshop-frontend:v1
    container_name: electroshop-frontend
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

