/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  LoginResponse,
  LogoutRequestRequest,
  LogoutResponse,
  RegisterResponse,
  TokenRefreshRequest,
  TokenRefreshResponse,
  UserLoginRequest,
  UserRegistrationRequest
} from '.././model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Authenticate user with email or phone number and password.
 * @summary User login
 */
export const authLoginCreate = (
    userLoginRequest: UserLoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LoginResponse>(
      {url: `/api/auth/login/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLoginRequest, signal
    },
      options);
    }
  


export const getAuthLoginCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLoginCreate>>, TError,{data: UserLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authLoginCreate>>, TError,{data: UserLoginRequest}, TContext> => {

const mutationKey = ['authLoginCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLoginCreate>>, {data: UserLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  authLoginCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authLoginCreate>>>
    export type AuthLoginCreateMutationBody = UserLoginRequest
    export type AuthLoginCreateMutationError = void

    /**
 * @summary User login
 */
export const useAuthLoginCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLoginCreate>>, TError,{data: UserLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLoginCreate>>,
        TError,
        {data: UserLoginRequest},
        TContext
      > => {

      const mutationOptions = getAuthLoginCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Logout the currently authenticated user and blacklist the refresh token. Send the refresh token in the request body to blacklist it.
 * @summary User logout
 */
export const authLogoutCreate = (
    logoutRequestRequest: LogoutRequestRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LogoutResponse>(
      {url: `/api/auth/logout/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutRequestRequest, signal
    },
      options);
    }
  


export const getAuthLogoutCreateMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogoutCreate>>, TError,{data: LogoutRequestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authLogoutCreate>>, TError,{data: LogoutRequestRequest}, TContext> => {

const mutationKey = ['authLogoutCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogoutCreate>>, {data: LogoutRequestRequest}> = (props) => {
          const {data} = props ?? {};

          return  authLogoutCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authLogoutCreate>>>
    export type AuthLogoutCreateMutationBody = LogoutRequestRequest
    export type AuthLogoutCreateMutationError = void | void

    /**
 * @summary User logout
 */
export const useAuthLogoutCreate = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogoutCreate>>, TError,{data: LogoutRequestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogoutCreate>>,
        TError,
        {data: LogoutRequestRequest},
        TContext
      > => {

      const mutationOptions = getAuthLogoutCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Refresh the access token using a valid refresh token.
 * @summary Refresh access token
 */
export const authRefreshCreate = (
    tokenRefreshRequest: TokenRefreshRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenRefreshResponse>(
      {url: `/api/auth/refresh/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRefreshRequest, signal
    },
      options);
    }
  


export const getAuthRefreshCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRefreshCreate>>, TError,{data: TokenRefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authRefreshCreate>>, TError,{data: TokenRefreshRequest}, TContext> => {

const mutationKey = ['authRefreshCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRefreshCreate>>, {data: TokenRefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  authRefreshCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthRefreshCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authRefreshCreate>>>
    export type AuthRefreshCreateMutationBody = TokenRefreshRequest
    export type AuthRefreshCreateMutationError = void

    /**
 * @summary Refresh access token
 */
export const useAuthRefreshCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRefreshCreate>>, TError,{data: TokenRefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authRefreshCreate>>,
        TError,
        {data: TokenRefreshRequest},
        TContext
      > => {

      const mutationOptions = getAuthRefreshCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Register a new user with email or phone number. At least one of email or phone must be provided.
 * @summary Register a new user
 */
export const authRegisterCreate = (
    userRegistrationRequest: UserRegistrationRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterResponse>(
      {url: `/api/auth/register/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRegistrationRequest, signal
    },
      options);
    }
  


export const getAuthRegisterCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRegisterCreate>>, TError,{data: UserRegistrationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authRegisterCreate>>, TError,{data: UserRegistrationRequest}, TContext> => {

const mutationKey = ['authRegisterCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRegisterCreate>>, {data: UserRegistrationRequest}> = (props) => {
          const {data} = props ?? {};

          return  authRegisterCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthRegisterCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authRegisterCreate>>>
    export type AuthRegisterCreateMutationBody = UserRegistrationRequest
    export type AuthRegisterCreateMutationError = void

    /**
 * @summary Register a new user
 */
export const useAuthRegisterCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRegisterCreate>>, TError,{data: UserRegistrationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authRegisterCreate>>,
        TError,
        {data: UserRegistrationRequest},
        TContext
      > => {

      const mutationOptions = getAuthRegisterCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    