/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for updating user password.
 */
export interface PasswordUpdateRequest {
  /**
   * Current password
   * @minLength 1
   */
  current_password: string;
  /**
   * New password
   * @minLength 1
   */
  new_password: string;
  /**
   * New password confirmation
   * @minLength 1
   */
  new_password_confirm: string;
}
