/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for refreshing access token.
 */
export interface TokenRefreshRequest {
  /** @minLength 1 */
  refresh: string;
}
