/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for user login.
 */
export interface UserLoginRequest {
  /** @minLength 1 */
  email_or_phone: string;
  /** @minLength 1 */
  password: string;
}
