/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for user login with optional OTP.
 */
export interface UserLoginRequest {
  /** @minLength 1 */
  email_or_phone: string;
  /**
   * Password for login (optional if OTP is provided)
   * @nullable
   */
  password?: string | null;
  /**
   * OTP code for login (optional, alternative to password)
   * @maxLength 6
   * @nullable
   */
  otp_code?: string | null;
}
