/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for user registration with optional OTP.
 */
export interface UserRegistrationRequest {
  /** @nullable */
  email?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  /** @nullable */
  password?: string | null;
  /**
   * OTP code for registration (required if password not provided)
   * @maxLength 6
   * @nullable
   */
  otp_code?: string | null;
}
