/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

export interface JWTTokens {
  /** JWT access token */
  access: string;
  /** JWT refresh token */
  refresh: string;
}
