/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for updating user profile.
 */
export interface PatchedUserUpdateRequest {
  /**
   * @maxLength 254
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
}
