/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for user registration.
 */
export interface UserRegistrationRequest {
  /** @nullable */
  email?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  password_confirm: string;
}
