/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for user profile.
 */
export interface User {
  readonly id: number;
  /**
   * @maxLength 254
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  readonly created_at: string;
  is_active?: boolean;
}
