# Generated by Django 6.0 on 2025-12-28 08:06

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record is soft deleted', verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted (if soft deleted)', null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record is soft deleted', verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted (if soft deleted)', null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False, verbose_name='ID')),
                ('specs_snapshot', models.JSONField(blank=True, default=dict)),
                ('color', models.ForeignKey(blank=True, help_text='Optional: the specific color selected for this offer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted', to='products.productoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'offer', 'color')},
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
