# Generated by Django 6.0 on 2025-12-29 19:46

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record is soft deleted', verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted (if soft deleted)', null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the user subscribed')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record is soft deleted', verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted (if soft deleted)', null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer name', max_length=100)),
                ('customer_title', models.CharField(blank=True, help_text='Customer title/position', max_length=100)),
                ('customer_image', models.ImageField(blank=True, help_text='Customer photo', upload_to='testimonials/%Y/%m/%d/')),
                ('testimonial_text', models.TextField(help_text='Testimonial content')),
                ('rating', models.PositiveIntegerField(help_text='Rating out of 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is a featured testimonial')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this testimonial is active')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-is_featured', '-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CountdownOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record is soft deleted', verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted (if soft deleted)', null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer title', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Offer subtitle', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Offer description')),
                ('deadline', models.DateTimeField(help_text='Countdown deadline')),
                ('countdown_label', models.CharField(default="Don't Miss!!", help_text='Label above the title', max_length=100)),
                ('background_image', models.ImageField(blank=True, help_text='Background image', upload_to='countdown/backgrounds/%Y/%m/%d/')),
                ('product_image', models.ImageField(blank=True, help_text='Product image', upload_to='countdown/products/%Y/%m/%d/')),
                ('background_color', models.CharField(default='#D0E9F3', help_text='Background color (hex code)', max_length=7)),
                ('button_text', models.CharField(default='Check it Out!', help_text='Button text', max_length=50)),
                ('button_link', models.URLField(blank=True, help_text='Button link URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this offer is active')),
                ('featured_product', models.ForeignKey(blank=True, help_text='Product to feature in this offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countdown_offers', to='products.product')),
            ],
            options={
                'verbose_name': 'Countdown Offer',
                'verbose_name_plural': 'Countdown Offers',
                'ordering': ['deadline'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record is soft deleted', verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted (if soft deleted)', null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline for the banner', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text="Small text above title (e.g., '30% Sale Off')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Banner description text')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage (1-100)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('discount_text', models.CharField(blank=True, help_text="Discount display text (e.g., 'UP TO 30% OFF')", max_length=50)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the banner', upload_to='hero/backgrounds/%Y/%m/%d/')),
                ('product_image', models.ImageField(blank=True, help_text='Product image to display', upload_to='hero/products/%Y/%m/%d/')),
                ('button_text', models.CharField(default='Shop Now', help_text='Button text', max_length=50)),
                ('button_link', models.URLField(blank=True, help_text='Button link URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in carousel')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is active')),
                ('featured_product', models.ForeignKey(blank=True, help_text='Product to feature in this banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='products.product')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record is soft deleted', verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was deleted (if soft deleted)', null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Banner subtitle', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Banner description')),
                ('banner_type', models.CharField(choices=[('big', 'Big Banner'), ('small_left', 'Small Banner (Left Aligned)'), ('small_right', 'Small Banner (Right Aligned)')], default='big', help_text='Banner layout type', max_length=20)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('discount_type', models.CharField(blank=True, help_text="Discount type (e.g., 'Flat 20% off', 'UP TO 40% off')", max_length=50)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the banner', upload_to='promo/backgrounds/%Y/%m/%d/')),
                ('product_image', models.ImageField(blank=True, help_text='Product image to display', upload_to='promo/products/%Y/%m/%d/')),
                ('background_color', models.CharField(blank=True, help_text='Background color (hex code, e.g., #FFFFFF)', max_length=7)),
                ('gradient_from', models.CharField(blank=True, help_text='Gradient start color (Tailwind class)', max_length=50)),
                ('gradient_to', models.CharField(blank=True, help_text='Gradient end color (Tailwind class)', max_length=50)),
                ('button_text', models.CharField(default='Shop Now', help_text='Button text', max_length=50)),
                ('button_link', models.URLField(blank=True, help_text='Button link URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is active')),
                ('featured_product', models.ForeignKey(blank=True, help_text='Product to feature in this banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners', to='products.product')),
            ],
            options={
                'verbose_name': 'Promo Banner',
                'verbose_name_plural': 'Promo Banners',
                'ordering': ['order', '-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
