/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  LoginResponse,
  LogoutRequestRequest,
  LogoutResponse,
  OTPRequestError,
  OTPRequestRequest,
  OTPRequestResponse,
  OTPVerifyError,
  OTPVerifyRequest,
  OTPVerifyResponse,
  RegisterResponse,
  TokenRefreshRequest,
  TokenRefreshResponse,
  UserLoginRequest,
  UserRegistrationRequest,
} from ".././models";

import { customInstance } from ".././mutator";
import type { ErrorType } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Authenticate user with email or phone number and password or OTP.
 * @summary User login
 */
export const authLoginCreate = (
  userLoginRequest: UserLoginRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LoginResponse>(
    {
      url: `/api/auth/login/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: userLoginRequest,
      signal,
    },
    options,
  );
};

export const getAuthLoginCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLoginCreate>>,
    TError,
    { data: UserLoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: UserLoginRequest },
  TContext
> => {
  const mutationKey = ["authLoginCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLoginCreate>>,
    { data: UserLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authLoginCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLoginCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLoginCreate>>
>;
export type AuthLoginCreateMutationBody = UserLoginRequest;
export type AuthLoginCreateMutationError = ErrorType<void>;

/**
 * @summary User login
 */
export const useAuthLoginCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLoginCreate>>,
      TError,
      { data: UserLoginRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: UserLoginRequest },
  TContext
> => {
  const mutationOptions = getAuthLoginCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Logout the currently authenticated user and blacklist the refresh token. Send the refresh token in the request body to blacklist it.
 * @summary User logout
 */
export const authLogoutCreate = (
  logoutRequestRequest: LogoutRequestRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LogoutResponse>(
    {
      url: `/api/auth/logout/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: logoutRequestRequest,
      signal,
    },
    options,
  );
};

export const getAuthLogoutCreateMutationOptions = <
  TError = ErrorType<void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogoutCreate>>,
    TError,
    { data: LogoutRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogoutCreate>>,
  TError,
  { data: LogoutRequestRequest },
  TContext
> => {
  const mutationKey = ["authLogoutCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogoutCreate>>,
    { data: LogoutRequestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authLogoutCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLogoutCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogoutCreate>>
>;
export type AuthLogoutCreateMutationBody = LogoutRequestRequest;
export type AuthLogoutCreateMutationError = ErrorType<void | void>;

/**
 * @summary User logout
 */
export const useAuthLogoutCreate = <
  TError = ErrorType<void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLogoutCreate>>,
      TError,
      { data: LogoutRequestRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLogoutCreate>>,
  TError,
  { data: LogoutRequestRequest },
  TContext
> => {
  const mutationOptions = getAuthLogoutCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Request an OTP code for registration or login. Rate limited: 3 requests max, 1 min cooldown, 1 hour lockout after 3 consecutive requests.
 * @summary Request OTP code
 */
export const authOtpRequestCreate = (
  oTPRequestRequest: OTPRequestRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<OTPRequestResponse>(
    {
      url: `/api/auth/otp/request/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: oTPRequestRequest,
      signal,
    },
    options,
  );
};

export const getAuthOtpRequestCreateMutationOptions = <
  TError = ErrorType<OTPRequestError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authOtpRequestCreate>>,
    TError,
    { data: OTPRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authOtpRequestCreate>>,
  TError,
  { data: OTPRequestRequest },
  TContext
> => {
  const mutationKey = ["authOtpRequestCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authOtpRequestCreate>>,
    { data: OTPRequestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authOtpRequestCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthOtpRequestCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authOtpRequestCreate>>
>;
export type AuthOtpRequestCreateMutationBody = OTPRequestRequest;
export type AuthOtpRequestCreateMutationError = ErrorType<OTPRequestError>;

/**
 * @summary Request OTP code
 */
export const useAuthOtpRequestCreate = <
  TError = ErrorType<OTPRequestError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authOtpRequestCreate>>,
      TError,
      { data: OTPRequestRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authOtpRequestCreate>>,
  TError,
  { data: OTPRequestRequest },
  TContext
> => {
  const mutationOptions = getAuthOtpRequestCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Verify an OTP code for registration or login.
 * @summary Verify OTP code
 */
export const authOtpVerifyCreate = (
  oTPVerifyRequest: OTPVerifyRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<OTPVerifyResponse>(
    {
      url: `/api/auth/otp/verify/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: oTPVerifyRequest,
      signal,
    },
    options,
  );
};

export const getAuthOtpVerifyCreateMutationOptions = <
  TError = ErrorType<OTPVerifyError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authOtpVerifyCreate>>,
    TError,
    { data: OTPVerifyRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authOtpVerifyCreate>>,
  TError,
  { data: OTPVerifyRequest },
  TContext
> => {
  const mutationKey = ["authOtpVerifyCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authOtpVerifyCreate>>,
    { data: OTPVerifyRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authOtpVerifyCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthOtpVerifyCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authOtpVerifyCreate>>
>;
export type AuthOtpVerifyCreateMutationBody = OTPVerifyRequest;
export type AuthOtpVerifyCreateMutationError = ErrorType<OTPVerifyError>;

/**
 * @summary Verify OTP code
 */
export const useAuthOtpVerifyCreate = <
  TError = ErrorType<OTPVerifyError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authOtpVerifyCreate>>,
      TError,
      { data: OTPVerifyRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authOtpVerifyCreate>>,
  TError,
  { data: OTPVerifyRequest },
  TContext
> => {
  const mutationOptions = getAuthOtpVerifyCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Refresh the access token using a valid refresh token.
 * @summary Refresh access token
 */
export const authRefreshCreate = (
  tokenRefreshRequest: TokenRefreshRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TokenRefreshResponse>(
    {
      url: `/api/auth/refresh/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: tokenRefreshRequest,
      signal,
    },
    options,
  );
};

export const getAuthRefreshCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRefreshCreate>>,
    TError,
    { data: TokenRefreshRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRefreshCreate>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  const mutationKey = ["authRefreshCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRefreshCreate>>,
    { data: TokenRefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authRefreshCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRefreshCreate>>
>;
export type AuthRefreshCreateMutationBody = TokenRefreshRequest;
export type AuthRefreshCreateMutationError = ErrorType<void>;

/**
 * @summary Refresh access token
 */
export const useAuthRefreshCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRefreshCreate>>,
      TError,
      { data: TokenRefreshRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authRefreshCreate>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  const mutationOptions = getAuthRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Register a new user with email or phone number. Supports both password and OTP-based registration.
 * @summary Register a new user
 */
export const authRegisterCreate = (
  userRegistrationRequest: UserRegistrationRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RegisterResponse>(
    {
      url: `/api/auth/register/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: userRegistrationRequest,
      signal,
    },
    options,
  );
};

export const getAuthRegisterCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegisterCreate>>,
    TError,
    { data: UserRegistrationRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegisterCreate>>,
  TError,
  { data: UserRegistrationRequest },
  TContext
> => {
  const mutationKey = ["authRegisterCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegisterCreate>>,
    { data: UserRegistrationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authRegisterCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRegisterCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRegisterCreate>>
>;
export type AuthRegisterCreateMutationBody = UserRegistrationRequest;
export type AuthRegisterCreateMutationError = ErrorType<void>;

/**
 * @summary Register a new user
 */
export const useAuthRegisterCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegisterCreate>>,
      TError,
      { data: UserRegistrationRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authRegisterCreate>>,
  TError,
  { data: UserRegistrationRequest },
  TContext
> => {
  const mutationOptions = getAuthRegisterCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
