/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */
import type { JWTTokens } from "./jWTTokens";
import type { User } from "./user";

export interface LoginResponse {
  tokens: JWTTokens;
  /** Success message */
  message: string;
  user: User;
}
