/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */
import type { PurposeEnum } from "./purposeEnum";

export interface OTPRequestResponse {
  /** Success message */
  message: string;
  /** Email or phone number where OTP was sent */
  identifier: string;
  /** Purpose of OTP request

* `register` - register
* `login` - login */
  purpose: PurposeEnum;
  /** OTP code (only in development mode) */
  otp_code?: string;
  /** Indicates if development mode is enabled */
  dev_mode?: boolean;
}
