/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */
import type { PurposeEnum } from "./purposeEnum";

export interface OTPVerifyResponse {
  /** Success message */
  message: string;
  /** Email or phone number that was verified */
  identifier: string;
  /** Purpose of OTP verification

* `register` - register
* `login` - login */
  purpose: PurposeEnum;
}
