/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */
import type { PurposeEnum } from "./purposeEnum";

/**
 * Serializer for verifying OTP with single identifier field.
 */
export interface OTPVerifyRequest {
  /**
   * Email address or phone number
   * @minLength 1
   */
  identifier: string;
  /**
   * 6-digit OTP code to verify
   * @minLength 6
   * @maxLength 6
   */
  otp_code: string;
  /** Purpose of OTP: register or login

* `register` - register
* `login` - login */
  purpose: PurposeEnum;
}
