/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ElectroShop API
 * E-commerce platform API with JWT authentication
 * OpenAPI spec version: 1.0.0
 */

export interface ValidationErrorResponse {
  /** Email validation errors */
  email?: string[];
  /** Phone validation errors */
  phone?: string[];
  /** First name validation errors */
  first_name?: string[];
  /** Last name validation errors */
  last_name?: string[];
  /** Current password validation errors */
  current_password?: string[];
  /** New password validation errors */
  new_password?: string[];
  /** New password confirmation validation errors */
  new_password_confirm?: string[];
  /** Non-field validation errors */
  non_field_errors?: string[];
}
